# Generated by Django 5.2.3 on 2025-06-21 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagecolor',
            old_name='color_hex',
            new_name='hex_color',
        ),
    ]
