# Generated by Django 5.2.3 on 2025-06-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_color_hex_imagecolor_hex_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecolor',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbs/'),
        ),
        migrations.AlterField(
            model_name='imagecolor',
            name='hex_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
